language:
    - java

services:
    - mysql

jdk:
    - oraclejdk8
    - openjdk7

before_install:
    - mysql -u root < script.sql

script:
    - mvn clean test
    - ls -lah

cache:
    directories:
        - $HOME/.m2   # Cache para las dependencias de maven

dist:
    - trusty

sudo:
    - false

notifications:
  email: false